routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WEB\SmsController;
use App\Http\Controllers\WEB\UsahaController;
use App\Http\Controllers\Web\PengusahaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

Route::group(['middleware' => 'auth'], function () {
    Route::group(['middleware' => ['permission:kelola usaha']], function () {
        Route::get('usaha/dashboard/', [UsahaController::class, 'dashboard'])->name('usaha.dashboard');
        Route::resource('usaha', UsahaController::class);
        Route::resource('sms', SmsController::class);
        Route::resource('pengusaha', PengusahaController::class);
        Route::post('/sms/write/', [SmsController::class, 'writeSms'])->name('sms.write');
    });
    Route::resource('usaha', UsahaController::class)->only([
        'create', 'update'
    ]);
});

require __DIR__ . '/auth.php';

app/Models/Usaha.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Usaha extends Model
{
    use HasFactory;

    protected $table = 'usaha';

    protected $fillable = [
        'user_id',
        'nama',
        'nib',
        'jenis',
        'perizinan_id',
        'jenis_badan_usaha_id',
        'aset',
        'rata_omset_perbulan',
        'karyawan_lk',
        'karyawan_pr',
        'kelurahan',
        'kecamatan',
        'sektor_usaha',
        'bidang_usaha',
        'modal',
        'sektor'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function perizinan()
    {
        return $this->hasMany(Perizinan::class, 'usaha_id');
    }

    public function jenisBadanUsaha()
    {
        return $this->belongsTo(JenisBadanUsaha::class, 'jenis_badan_usaha_id');
    }

    public function gambar()
    {
        return $this->hasMany(Foto::class, 'usaha_id');
    }
}

app/Http/Controllers/API/UsahaController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Foto;
use App\Models\User;
use App\Models\Usaha;
use App\Models\Perizinan;
use Tymon\JWTAuth\Facades\JWTAuth;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreRequestUsaha;
use App\Http\Requests\UpdateRequestUsaha;
use Illuminate\Http\Request;

class UsahaController extends Controller
{

    public function index()
    {
        $relasiUsaha = Usaha::with('user', 'jenisBadanUsaha', 'gambar', 'perizinan', 'perizinan.kbli')->get();
        return response()->json($relasiUsaha, 200);
    }

    public function usahaById($id)
    {
        //Mencari User Yang Login Berdasarkan Token
        $user = JWTAuth::User();
        foreach ($user->roles as $role) {
            $roleName = $role->name;
        }

        //Mencari usaha Berdasarkan Id usaha
        $usahaId = Usaha::where('id', $id)->get();
        foreach ($usahaId as $usaha) {
            $userId = $usaha->user_id;
        }

        //Jika Rolenya Pengusaha dan id usernya tidak sama dengan id user yang ada di usaha 
        if ($roleName === 'pengusaha' && $user->id != $userId) {
            return response()->json([
                'message' => 'Anda hanya bisa melihat usaha anda sendiri'
            ], 403);
        }
        $usahaById = Usaha::where('id', $id)->with('user', 'jenisBadanUsaha', 'gambar', 'perizinan', 'perizinan.kbli')->get();
        return response()->json($usahaById, 200);
    }

    public function store(StoreRequestUsaha $request)
    {
        //input user
        $user = new User;
        $user->nik            = $request->nik;
        $user->nama           = $request->nama;
        $user->jenis_kelamin  = $request->jenis_kelamin;
        $user->no_hp          = $request->no_hp;
        $user->alamat         = $request->alamat;
        $user->password       = bcrypt(strtolower(preg_replace("/[^a-zA-Z]/", "", $request->nama)) . "123");
        $user->save();

        //menetapkan role pengusaha
        $userById = User::find($user->id);
        $userById->assignRole('pengusaha');

        //input data usaha
        $usaha = new Usaha(
            [
                'nama'                  => $request->data_usaha['nama_usaha'],
                'nib'                   => $request->data_usaha['nib'],
                'jenis'                 => $request->data_usaha['jenis_usaha'],
                'jenis_badan_usaha_id'  => $request->data_usaha['jenis_badan_usaha'],
                'alamat'                => $request->data_usaha['alamat_usaha'],
                'aset'                  => $request->data_usaha['aset'],
                'rata_omset_perbulan'   => $request->data_usaha['rata_omset_perbulan'],
                'karyawan_lk'           => $request->data_usaha['karyawan_lk'],
                'karyawan_pr'           => $request->data_usaha['karyawan_pr'],
            ]
        );

        $saveUsaha =  $userById->usaha()->save($usaha);

        //input data izin
        foreach ($request->perizinan as $izin) {
            $perizinan = new Perizinan(
                [
                    'tanggal'       => $izin['tanggal'],
                    'iumk_nomor'    => $izin['iumk_nomor'],
                    'kbli_id'       => $izin['kbli_id']
                ]
            );
            $usahaById = Usaha::find($saveUsaha->id);
            $usahaById->perizinan()->save($perizinan);
        }



        // input gambar logo
        $imgLogoName = 'logo_' . $request->file('logo')->hashName();
        $request->file('logo')->storeAs('public/uploads/img', $imgLogoName);
        $gambarLogo = new Foto(
            [
                'foto'          => 'storage/uploads/img/' . $imgLogoName,
                'jenis'    => "logo",
                'nama'     => "Logo " . $saveUsaha->nama_usaha
            ]
        );
        $usahaById = Usaha::find($saveUsaha->id);
        $usahaById->gambar()->save($gambarLogo);

        //input gambar produk
        foreach ($request->file('produk') as $key => $imgProduk) {
            $imgProdukName      = 'produk_' . $imgProduk->hashName();
            $imgProduk->storeAs('public/uploads/img', $imgProdukName);
            $gambarProduk  = new Foto(
                [
                    'foto'          => 'storage/uploads/img/' . $imgProdukName,
                    'jenis'    => "produk",
                    'nama'     => "Produk " . $key + 1
                ]
            );
            $usahaById = Usaha::find($saveUsaha->id);
            $usahaById->gambar()->save($gambarProduk);
        }

        //input gambar lokasi
        foreach ($request->file('lokasi') as $key => $imgLokasi) {
            $imgLokasiName      = 'lokasi_' . $imgLokasi->hashName();
            $imgLokasi->storeAs('public/uploads/img', $imgLokasiName);
            $gambarLokasi  = new Foto(
                [
                    'foto'          => 'storage/uploads/img/' . $imgLokasiName,
                    'jenis'    => "lokasi",
                    'nama'     => "Lokasi " . $key + 1
                ]
            );
            $usahaById = Usaha::find($saveUsaha->id);
            $usahaById->gambar()->save($gambarLokasi);
        }

        $relasiUsahaById = Usaha::where('id', $saveUsaha->id)->with('user', 'jenisBadanUsaha', 'gambar', 'perizinan', 'perizinan.kbli')->get();
        return response()->json([
            'message'   => 'Success',
            'data'      => $relasiUsahaById
        ], 200);
    }

    public function destroy($id)
    {
        $usaha = Usaha::find($id);
        $user = User::find($usaha->user_id);

        if (is_null($usaha)) {
            return response()->json("Data Not Found", 404);
        }

        $fotoByUsahaId = Foto::where('usaha_id', $id)->get();
        foreach ($fotoByUsahaId as $foto) {
            $imagePath = public_path() . '/' . $foto->foto;
            unlink($imagePath);
        }

        $hapusSuccess = $user->delete();

        if (!$hapusSuccess) {
            return response()->json("Error Delete", 500);
        } else {
            return response()->json("$usaha->nama with id $id has been deleted", 200);
        }
    }

    public function update(UpdateRequestUsaha $request, $id)
    {

        //Mencari Role Name Sesuai User yang login
        $userLogin = JWTAuth::User();
        foreach ($userLogin->roles as $role) {
            $role_name = $role->name;
        }

        if ($role_name === 'pengusaha' && $id != $userLogin->id) {
            return response()->json([
                'message' => 'Anda hanya bisa mengupdate usaha anda sendiri'
            ], 403);
        }

        //Mencari Usaha Sesuai Id Usaha
        $usahaById = Usaha::find($id);
        $userById = User::find($usahaById->user_id);

        // Update User
        $password = bcrypt(strtolower(preg_replace("/[^a-zA-Z]/", "", $request->nama)) . "123");
        $arrayUser = array(

            'nik'           => $request->nik,
            'nama'          => $request->nama,
            'jenis_kelamin' => $request->jenis_kelamin,
            'no_hp'         => $request->no_hp,
            'alamat'        => $request->alamat,
            'password'      => $password

        );
        $userById->update($arrayUser);

        //Update data usaha
        $arrayUsaha = array(
            'nama'            => $request->data_usaha['nama_usaha'],
            'nib'                   => $request->data_usaha['nib'],
            'jenis'           => $request->data_usaha['jenis_usaha'],
            'jenis_badan_usaha_id'  => $request->data_usaha['jenis_badan_usaha'],
            'alamat'          => $request->data_usaha['alamat_usaha'],
            'aset'                  => $request->data_usaha['aset'],
            'rata_omset_perbulan'   => $request->data_usaha['rata_omset_perbulan'],
            'karyawan_lk'           => $request->data_usaha['karyawan_lk'],
            'karyawan_pr'           => $request->data_usaha['karyawan_pr'],
        );
        $userById->usaha()->update($arrayUsaha);


        if ($request->has('perizinan')) {
            //Hapus Perizinan
            $perizinanByUsahaId = Perizinan::where('usaha_id', $id)->get();
            foreach ($perizinanByUsahaId as $perizinanByUsahaId) {
                $perizinanByUsahaId->delete();
            }
            //Update data izin
            foreach ($request->perizinan as $izin) {
                $izin = new Perizinan(
                    [
                        'tanggal'       => $izin['tanggal'],
                        'iumk_nomor'    => $izin['iumk_nomor'],
                        'kbli_id'       => $izin['kbli_id']
                    ]
                );
                $usahaById->perizinan()->save($izin);
            }
        }


        if ($request->has('logo')) {
            //Hapus Gambar
            $gambarByUsahaId = Foto::where(['usaha_id' => $id, 'jenis' => 'logo'])->get();

            if ($gambarByUsahaId->all() != null) {
                $imagePath = public_path() . '/' . $gambarByUsahaId[0]->foto;
                unlink($imagePath);
                $gambarByUsahaId[0]->delete();
            }


            // Update gambar logo
            $imgLogoName = 'logo_' . $request->file('logo')->hashName();
            $request->file('logo')->storeAs('public/uploads/img', $imgLogoName);
            $gambarLogo = new Foto(
                [
                    'foto'          => 'storage/uploads/img/' . $imgLogoName,
                    'jenis'         => "logo",
                    'nama'          => "Logo " . $usahaById->nama_usaha
                ]
            );
            $usahaById->gambar()->save($gambarLogo);
        }

        //hapus gambar produk
        if ($request->has('imgproduk_id')) {
            foreach ($request->imgproduk_id as $key => $produkId) {
                $gambarById = Foto::where(['id' => $produkId, 'jenis' => 'produk'])->get();
                $imagePath = public_path() . '/' . $gambarById[0]->foto;

resources/views/usaha/dashboard.blade.php
@extends('layouts.main')

@section('container')
    <div style="margin-right:25%;">
        <h2 class="fw-bold mb-5">
            Dashboard UKM
        </h2>

        <div class="row align-items-start" style="width:100%;">
            {{-- RATA OMSET PERBULAN --}}
            <div class="col-7 mb-5 me-5 p-3 card-dashboard" style=" height:20rem;">
                <h5 class="ms-4 mb-2 fw-bold">Omset perbulan UKM</h5>
                <div style="width: 100%; height:90%">
                    <canvas id="omsetperbulan" height="130">
                    </canvas>
                </div>
            </div>

            {{-- UKM PRIA DAN WANITA --}}
            <div class="col mb-3 p-3 card-dashboard" style="width:30%;  height:20rem;">

                <td>

                    <div class="row align-items-start" style="width: 100%; height:45%">
                        <div class="col-5 relative">

                            <canvas id="ukmpria" height="130">
                            </canvas>
                            <div class="absolute-center text-center">
                                <p style="margin: 0%" class="fs-3 fw-bold">74%</p>
                            </div>
                        </div>
                        <div class="col relative" style="height:100%">
                            <div class="absolute-center-left">
                                <h4 style="margin: 0%" class="fw-bold">UKM Pria</h4>
                                <p style="margin: 0%; color: gray;" class="fs-6">tahun 2021/2022</p>
                            </div>
                        </div>

                    </div>

                </td>
                <br>
                <td>
                    <div class="row align-items-start" style=" width: 100%; height:45%">
                        <div class="col-5 relative">
                            <canvas id="ukmwanita" height="130">
                            </canvas>
                            <div class="absolute-center text-center">
                                <p style="margin: 0%" class="fs-3 fw-bold">26%</p>
                            </div>

                        </div>
                        <div class="col relative" style="height:100%">
                            <div class="absolute-center-left">
                                <h4 style="margin: 0%" class="fw-bold">UKM Wanita</h4>
                                <p style="margin: 0%; color: gray;" class="fs-6">tahun 2021/2022</p>
                            </div>
                        </div>

                    </div>
                </td>



            </div>
        </div>

        <div class="row align-items-start" style="width: 100%">

            <div style="height: 40rem" class="col-4 mb-5 me-4 p-5 card-dashboard">
                <p class="fs-5 fw-bold mb-3">Omset Perbulan <br> UKM Terbesar</p>
                @for ($i = 0; $i < 5; $i++)
                    <div class="card-list p-3 mb-3">
                        <p class="fs-5" style="margin: 0px;">Hafizi Iqbal</p>
                        <p class="label-p">Fizi Water Corporation</p>
                    </div>
                @endfor

            </div>


            <div style="height: 40rem;width: 30%;" class="col mb-5 p-5 card-dashboard">

                <div class="row mb-5">
                    <h5 class="fw-bold">Karyawan Pria</h5>
                    <p class="label-p mb-3" style="font-size: 14px">tahun 2021/2022</p>
                    <div style="width: 100%; height:90%">
                        <div id="progressLk" class="cont-progressbar">
                            <div id="fillProgressLk" style="background-color: black;" class="cont-progressbar">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mb-5">
                    <h5 class="fw-bold">Karyawan Wanita</h5>
                    <p class="label-p mb-3" style="font-size: 14px">tahun 2021/2022</p>
                    <div style="width: 100%; height:90%">
                        <div id="progressPr" class="cont-progressbar">
                            <div id="fillProgressPr" style="background-color: black;" class="cont-progressbar">
                            </div>
                        </div>
                    </div>
                </div>


                <div class="row mb-3">
                    <h5 class="fw-bold">Jenis-Jenis Badan Usaha</h5>
                    <div style="width: 100%; height:17rem">
                        <canvas id="jenisBadanUsaha" height="130">
                        </canvas>
                    </div>
                </div>
            </div>


        </div>

    </div>

    </div>
    @push('scriptchart')
        <script>
            const omsetperbulan = document.getElementById('omsetperbulan').getContext('2d');
            const myChart = new Chart(omsetperbulan, {
                type: 'bar',
                data: {
                    labels: ['< 100jt', '100 - 200jt', '200 - 300jt', '300 - 500jt'],
                    datasets: [{
                        data: [130, 220, 180, 60],
                        backgroundColor: '#000000',
                        hoverBackgroundColor: '#b4b3b3',
                        borderRadius: 15,
                        barThickness: 45,
                        borderSkipped: false
                    }]
                },
                options: {
                    maintainAspectRatio: false,
                    plugins: {
                        legend: {
                            display: false,
                        },
                    },
                    scales: {
                        y: {
                            grid: {
                                drawBorder: false
                            },
                            beginAtZero: true,
                            ticks: {
                                font: {
                                    size: 12,
                                    family: 'Poppins'
                                }
                            }
                        },
                        x: {
                            grid: {
                                display: false,
                            },
                            ticks: {
                                font: {
                                    size: 12,
                                    family: 'Poppins'
                                }
                            }
                        },
                    }
                }
            });

            const ukmpria = document.getElementById('ukmpria').getContext('2d');
            const ukmpriaChart = new Chart(ukmpria, {
                type: 'doughnut',
                data: {
                    labels: ['UKM PRIA'],
                    datasets: [{
                        data: [74, 26],
                        backgroundColor: ['#000000', '#c2c0c0'],
                        borderRadius: [5, 0],
                        cutout: '80%',
                        borderWidth: 0,
                        rotation: 140
                    }]
                },
                options: {
                    transitions: {
                        active: {
                            animation: {
                                duration: 400
                            }
                        }
                    },
                    maintainAspectRatio: false,
                    plugins: {
                        legend: {
                            display: false,
                        },
                    },
                }
            });
            const ukmwanita = document.getElementById('ukmwanita').getContext('2d');
            const ukmWanitaChart = new Chart(ukmwanita, {
                type: 'doughnut',
                data: {
                    labels: ['UKM WANITA'],
                    datasets: [{
                        data: [26, 74],
                        backgroundColor: ['#000000', '#c2c0c0'],
                        borderRadius: [5, 0],
                        cutout: '80%',
                        borderWidth: 0,
                        rotation: 40
                    }]
                },
                options: {
                    maintainAspectRatio: false,
                    plugins: {
                        legend: {
                            display: false,
                        },
                    },
                }








            });

            function myFunction() {
                var i = 0;
                if (i == 0) {
                    i = 1;
                    var elemLk = document.getElementById('fillProgressLk');
                    var elemPr = document.getElementById('fillProgressPr');
                    var widthLk = 1;
                    var widthPr = 1;
                    var idLk = setInterval(frameLk, 10);
                    var idPr = setInterval(framePr, 10);

                    function frameLk() {
                        if (widthLk >= 74) {
                            clearInterval(idLk);
                            i = 0;
                        } else {
                            widthLk++;
                            elemLk.style.width = widthLk + "%";
                        }
                    }

                    function framePr() {
                        if (widthPr >= 26) {
                            clearInterval(idPr);
                            i = 0;
                        } else {
                            widthPr++;
                            elemPr.style.width = widthPr + "%";
                        }
                    }
                }




            }

            const jenisBadanUsaha = document.getElementById('jenisBadanUsaha').getContext('2d');
            const jenisBadanUsahaChart = new Chart(jenisBadanUsaha, {
                type: 'bar',
                data: {
                    labels: [
                        "PT", "CV", "Koperasi", "Perorangan"
                    ],
                    datasets: [{
                        label: "Jumlah UKM",
                        data: [10, 40, 55, 33],
                        backgroundColor: '#000000',
                        borderRadius: 15,
                        barThickness: 25,
                    }]
                },
                options: {
                    indexAxis: 'y',
                    elements: {
                        bar: {
                            borderWidth: 2,
                        }
                    },

                    maintainAspectRatio: false,
                    plugins: {
                        legend: {
                            display: false
                        }
                    },
                    scales: {
                        y: {
                            grid: {
                                display: false,
                                drawBorder: false
                            },
                            beginAtZero: true,
                            ticks: {
                                padding: 10,
                                crossAlign: "far",
                                align: 'start',
                                font: {
                                    size: 12,
                                    family: 'Poppins'
                                }
                            }
                        },
                        x: {
                            ticks: {
                                font: {
                                    size: 12,
                                    family: 'Poppins',
                                }
                            }
                        },
                    },

                }
            })
        </script>
    @endpush

@endsection

resources/views/usaha/listumkm.blade.php
@extends('layouts.main')

@section('container')

    <div style="margin-right:25%">
        @if (session('message'))
            <div style="width: 100%" class="alert alert-success">{{ session('message') }}</div>
        @endif

        @if (session('messageError'))
            <div style="width: 100%" class="alert alert-danger">{{ session('messageError') }}</div>
        @endif

        <h2 class="fw-bold mb-5">
            Data List UKM Singkawang
        </h2>

        <table class="table table-striped display nowrap" id="usahatable">
            <thead>
                <tr>
                    <th scope="col">NO</th>
                    <th scope="col">Nama Pemilik Usaha</th>
                    <th scope="col">Nama Usaha</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($daftarUsaha as $key => $usaha)
                    <tr>
                        <th scope="row">{{ $key + 1 }}</th>
                        <td>{{ $usaha->user->nama }}</td>
                        <td>{{ $usaha->nama }}</td>
                        <td>
                            <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                action="{{ route('usaha.destroy', $usaha->id) }}" method="POST">
                                <a href="{{ route('usaha.edit', $usaha->id) }}"
                                    class="btn btn-sm btn-outline-warning">EDIT</a>
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-outline-danger">HAPUS</button>
                            </form>
                        </td>
                    </tr>

                @endforeach
            </tbody>
        </table>
    </div>

    @push('dataTableListUkm')
        <script>
            $(document).ready(function() {
                $('#usahatable').DataTable({
                    dom: 'lBfrtip',
                    buttons: [
                        'copy', 'csv', 'excel', 'pdf', 'print'
                    ]
                });
            });
        </script>
    @endpush
@endsection