routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WEB\SmsController;
use App\Http\Controllers\WEB\UsahaController;
use App\Http\Controllers\Web\PengusahaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

Route::group(['middleware' => 'auth'], function () {
    Route::group(['middleware' => ['permission:kelola usaha']], function () {
        Route::get('usaha/dashboard/', [UsahaController::class, 'dashboard'])->name('usaha.dashboard');
        Route::resource('usaha', UsahaController::class);
        Route::resource('sms', SmsController::class);
        Route::resource('pengusaha', PengusahaController::class);
        Route::post('/sms/write/', [SmsController::class, 'writeSms'])->name('sms.write');
    });
    Route::resource('usaha', UsahaController::class)->only([
        'create', 'update'
    ]);
});

require __DIR__ . '/auth.php';

app/Http/Controllers/WEB/PengusahaController.php
<?php

namespace App\Http\Controllers\Web;

use App\Models\User;
use App\Models\Usaha;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Pengusaha\StorePengusahaRequest;
use App\Http\Requests\Pengusaha\UpdatePengusahaRequest;
use App\Http\Requests\StoreRequestPengusaha;

class PengusahaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $daftarPengusaha = User::role('pengusaha')->get();
        return view('pengusaha.listpengusaha')->with(['tittle' => 'LIST PENGUSAHA', 'daftarPengusaha' => $daftarPengusaha]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('pengusaha.create', ['tittle' => 'PENDAFTARAN PENGUSAHA']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePengusahaRequest $request)
    {
        //input user
        $user = new User;
        $user->nik            = $request->nik;
        $user->nama           = $request->nama;
        $user->jenis_kelamin  = $request->jenis_kelamin;
        $user->no_hp          = $request->no_hp;
        $user->alamat         = $request->alamat;
        $user->password       = bcrypt(strtolower(preg_replace("/[^a-zA-Z]/", "", $request->nama)) . "123");
        $user->save();

        //menetapkan role pengusaha
        $userById = User::find($user->id);
        $userById->assignRole('pengusaha');

        return redirect()->route('pengusaha.create')->with(['message' => 'Pengusaha Baru Berhasil Diinput']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pengusahaById = User::where('id', $id)->get();

        return view('pengusaha.edit')->with(['tittle' => 'EDIT', 'pengusahaById' => $pengusahaById]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePengusahaRequest $request, $id)
    {
        //Mencari Usaha Sesuai Id Usaha
        $userById = User::find($id);

        // Update User
        $password = bcrypt(strtolower(preg_replace("/[^a-zA-Z]/", "", $request->nama)) . "123");
        $arrayUser = array(

            'nik'           => $request->nik,
            'nama'          => $request->nama,
            'jenis_kelamin' => $request->jenis_kelamin,
            'no_hp'         => $request->no_hp,
            'alamat'        => $request->alamat,
            'password'      => $password

        );
        $userById->update($arrayUser);
        return redirect()->route('pengusaha.index')->with(['message' => 'Pengusaha berhasil diupdate']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pengusaha/create.blade.php
@extends('layouts.main')

@section('container')

    @if (session('message'))
        <div style="width: 70%" class="alert alert-success">
            {{ session('message') }}
        </div>
    @endif
    @if ($errors->any())
        <div style="width:70%" class="alert alert-danger">
            <p><strong>Opps Ada Yang Harus Diperbaiki</strong></p>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <h2 class="fw-bold mb-5">
        Pendaftaran Pengusaha
    </h2>
    <form action="{{ route('pengusaha.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        {{-- NIK --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Nomor Induk Kependudukan (NIK)</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <input type="number" pattern="[0-9.]+" class="form-control p-2" aria-describedby="emailHelp" name="nik"
                        required>
                </div>
            </div>
        </div>

        {{-- Nama Pemilik Usaha --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Nama Pemilik Usaha (sesuai KTP)</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <input type="text" class="form-control p-2" name="nama" required>
                </div>
            </div>
        </div>

        {{-- Jenis Kelamin --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Jenis Kelamin</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-4 d-flex">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="jenis_kelamin" id="flexRadioDefault1"
                            value="Laki-Laki">
                        <label class="form-check-label" for="flexRadioDefault1">
                            Laki-Laki
                        </label>
                    </div>
                    &emsp;
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="jenis_kelamin" id="flexRadioDefault2"
                            value="Perempuan" checked>
                        <label class="form-check-label" for="flexRadioDefault2">
                            Perempuan
                        </label>
                    </div>
                </div>
            </div>
        </div>

        {{-- Alamat --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Alamat Tempat Tinggal</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <textarea class="form-control" name="alamat" id="floatingTextarea2" style="height: 150px"
                        required></textarea>
                </div>
            </div>
        </div>

        {{-- No Hp --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">No. Handphone</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <input type="number" pattern="[0-9.]+" class="form-control p-2" name="no_hp" required>
                </div>
            </div>
        </div>



        <div class="row align-items-start">
            <div class="col- mb-4">
                <button type="submit" class="btn btn-dark" style="width: 70%">SIMPAN UKM BARU</button>
            </div>
        </div>

    </form>




@endsection

resources/views/pengusaha/edit.blade.php
@extends('layouts.mainedit')

@section('container')
    <div style="margin-left:15%; margin-right:15%">
        @if ($errors->any())
            <div style="width:100%" class="alert alert-danger">
                <p><strong>Opps Ada Yang Harus Diperbaiki</strong></p>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <a href="{{ route('usaha.index') }}"><button class="btn btn-secondary">
                << Back</button></a>

        <h2 class="fw-bold mb-5 text-center">
            Memperbaru Data Pengusaha
        </h2>

        <h3 class="mb-4">
            A. Data Pemilik Usaha
        </h3>

        <form action="{{ route('pengusaha.update', $pengusahaById[0]->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')

            <input type="hidden" name="id" value="{{ $pengusahaById[0]->id }}">
            {{-- NIK --}}
            <div class="row align-items-start">
                <div class="p-2 mb-5 mt-3" style="width:35%;">
                    <label style="font-size: 17px">Nomor Induk Kependudukan (NIK)</label>
                </div>
                <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                    :
                </div>
                <div class="col">
                    <div class="mb-5 mt-3">
                        <input type="number" pattern="[0-9.]+" class="form-control p-2" aria-describedby="emailHelp"
                            name="nik" value="{{ $pengusahaById[0]->nik }}" required>
                    </div>
                </div>
            </div>

            {{-- Nama Pemilik Usaha --}}
            <div class="row align-items-start">
                <div class="p-2 mb-5 mt-3" style="width:35%;">
                    <label style="font-size: 17px">Nama Pemilik Usaha (sesuai KTP)</label>
                </div>
                <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                    :
                </div>
                <div class="col">
                    <div class="mb-5 mt-3">
                        <input type="text" class="form-control p-2" name="nama" required
                            value="{{ $pengusahaById[0]->nama }}">
                    </div>
                </div>
            </div>

            {{-- Jenis Kelamin --}}
            <div class="row align-items-start">
                <div class="p-2 mb-5 mt-3" style="width:35%;">
                    <label style="font-size: 17px">Jenis Kelamin</label>
                </div>
                <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                    :
                </div>
                <div class="col">
                    <div class="mb-5 mt-4 d-flex">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="jenis_kelamin" id="flexRadioDefault1"
                                value="Laki-Laki" {{ $pengusahaById[0]->jenis_kelamin == 'Laki-Laki' ? 'checked' : '' }}>
                            <label class="form-check-label" for="flexRadioDefault1">
                                Laki-Laki
                            </label>
                        </div>
                        &emsp;
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="jenis_kelamin" id="flexRadioDefault2"
                                value="Perempuan" {{ $pengusahaById[0]->jenis_kelamin == 'Perempuan' ? 'checked' : '' }}>
                            <label class="form-check-label" for="flexRadioDefault2">
                                Perempuan
                            </label>
                        </div>
                    </div>
                </div>
            </div>

            {{-- Alamat --}}
            <div class="row align-items-start">
                <div class="p-2 mb-5 mt-3" style="width:35%;">
                    <label style="font-size: 17px">Alamat Tempat Tinggal</label>
                </div>
                <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                    :
                </div>
                <div class="col">
                    <div class="mb-5 mt-3">
                        <textarea class="form-control" name="alamat" id="floatingTextarea2" style="height: 150px"
                            required>{{ $pengusahaById[0]->alamat }}</textarea>
                    </div>
                </div>
            </div>

            {{-- No Hp --}}
            <div class="row align-items-start">
                <div class="p-2 mb-5 mt-3" style="width:35%;">
                    <label style="font-size: 17px">No. Handphone</label>
                </div>
                <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                    :
                </div>
                <div class="col">
                    <div class="mb-5 mt-3">
                        <input type="number" pattern="[0-9.]+" class="form-control p-2" name="no_hp"
                            value="{{ $pengusahaById[0]->no_hp }}" required>
                    </div>
                </div>
            </div>

            <div class="row align-items-start">
                <div class="col- mb-4">
                    <button type="submit" class="btn btn-dark" style="width: 100%">Perbaharui Data Pengusaha</button>
                </div>
            </div>

        </form>
    </div>

@endsection

resources/views/pengusaha/listpengusaha.blade.php
@extends('layouts.main')

@section('container')

    <div style="margin-right:25%">
        @if (session('message'))
            <div style="width: 100%" class="alert alert-success">{{ session('message') }}</div>
        @endif

        @if (session('messageError'))
            <div style="width: 100%" class="alert alert-danger">{{ session('messageError') }}</div>
        @endif

        <h2 class="fw-bold mb-5">
            List Pengusaha UKM Singkawang
        </h2>

        <table class="table table-striped" id="usahatable">
            <thead>
                <tr>
                    <th scope="col">NO</th>
                    <th scope="col">NIK</th>
                    <th scope="col">Nama Pengusaha</th>
                    <th scope="col">Jenis Kelamin</th>
                    <th scope="col">No. HP</th>
                    <th scope="col">Alamat</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($daftarPengusaha as $key => $pengusaha)
                    <tr>
                        <th scope="row">{{ $key + 1 }}</th>
                        <td>{{ $pengusaha->nik }}</td>
                        <td>{{ $pengusaha->nama }}</td>
                        <td>{{ $pengusaha->jenis_kelamin }}</td>
                        <td>{{ $pengusaha->no_hp }}</td>
                        <td>{{ \Illuminate\Support\Str::limit($pengusaha->alamat, 10) }}</td>
                        <td>
                            <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                action="{{ route('usaha.destroy', $pengusaha->id) }}" method="POST">
                                <a href="{{ route('pengusaha.edit', $pengusaha->id) }}"
                                    class="btn btn-sm btn-outline-warning">EDIT</a>
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-outline-danger">HAPUS</button>
                            </form>
                        </td>
                    </tr>

                @endforeach
            </tbody>
        </table>
    </div>

    @push('dataTableListUkm')
        <script>
            $(document).ready(function() {
                $('#usahatable').DataTable({
                    dom: 'lBfrtip',
                    buttons: [
                        'copy', 'csv', 'excel', 'pdf', 'print'
                    ]
                });

            });
        </script>
    @endpush
@endsection